#!/bin/sh
# This script is a shortcut to generate an apt "resources" file (links to existing files in apt format) by invoking the myApt jar file expected in the bin directory.
# Expected parameter: the relative path to the directory to browse
# Usage example: "myAptResources src/site/resources/"
# To add svn rcs keyword (Id Date URL Author Revision) in the apt file, add the "svn" as a second option
# Example: "myAptResources src/site/resources svn"

# eventual second option to inject rcs keywords in the apt
SCM=$2

# appends the "-Dscm=" with the eventual third user input (overwritten to an empty string if the third option is not given)
SCM_OPTION="-Dscm="$2

# checks user input second parameter (svn), if empty, sets an empty string for the third parameter
if [ -z "$SCM" ]
then
   SCM_OPTION=""
fi

# launches the command
java -jar ~/bin/myApt_20150512.jar -Dtype=resources -DresourcesDir=$1 $SCM_OPTION
