#!/bin/sh
# This script is a shortcut to invoke the myApt jar file expected in the bin directory with options to generate a set of "images" apt file
# Expected parameter: the path to a directory containing images
# Usage example: "myAptImageDir src/site/resources/images/"
java -jar ~/bin/myApt_20150512.jar -DimageDir=$1
